### ISSUE TITLE
Craft 4 support

### ISSUE THREAD

**Issue by wmdhosting** [TopShelfCraft/Scraper#5]
any info about Craft 4.. support thx

**Comment by gixxy22** [comment]
Also looking for update for craft 4. Thanks

**Comment by viesrood** [comment]
Currently, the only plugin that's stopping me to upgrade to Craft 4. It would be nice to have Scraper updated. It should be a lot less work than with Craft 3.

**Comment by michaelrog** [comment]
Craft 4 version is in the works! Thanks, yall!

**Comment by viesrood** [comment]
Do you have any idea when the Craft version 4 will be ready?

**Comment by wmdhosting** [comment]
is this close..  now..

**Comment by wmdhosting** [comment]
we are humans :)

**Comment by michaelrog** [comment]
Just tagged `4.0.0` for Craft 4 support! 🚀
