### ISSUE TITLE
Craft 5 in the future?

### ISSUE THREAD

**Issue by aarmitage** [TopShelfCraft/Scraper#8]
Hi Michael,

This plugin looks like it will help us with a project, but I'm wondering if there'll be a Craft 5 version?

The usage numbers look low and it's been a while since any updates, so don't want to make a promise if it leaves a client stuck on C4.

We could maybe fork it and look at updating it ourselves, but that would have an impact on the project we're currently considering this for.

Cheers,
Andrew

**Comment by michaelrog** [comment]
Hey Andrew — Yes, I do plan to upgrade Scraper for Craft 5 support! It's a niche need, to be sure, but I still use this one myself for a couple clients. 👍🏼
